# Generated by Django 4.2.11 on 2025-12-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('feccre', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('fecmod', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado')),
                ('creadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('feccre', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('fecmod', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado')),
                ('creadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Etiqueta')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre')),
                ('valor', models.FloatField(default=0.0, verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('feccre', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('fecmod', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modificado')),
                ('creadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificadopor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.tipo', verbose_name='Tipo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.ubicacion', verbose_name='Ubicacion')),
            ],
            options={
                'ordering': ['ubicacion', 'nombre'],
            },
        ),
    ]
